version: "3"

services:

  backend:
    image: fastapi-search-backend:0.0.1
    ports:
      - "8000:8000"
    volumes:
      - ./api/alembic:/api/alembic
      - ./api/app:/api/app
    command: >
      bash -c '''alembic revision --autogenerate -m "My Commit" &
                 alembic upgrade head &
                 uvicorn app.src.main:app --host 0.0.0.0'''
    restart: on-failure:3
    depends_on:
      - db

  db:
    image: postgres:15.1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pgFastApiPass
      POSTGRES_DB: search_app
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 10s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data


volumes:
  pg_data:
    driver: local